#!/bin/bash

# From Documentation
# https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/080_register_stakepool.md

# Init vars
source /scripts/functions/check_balance
source /scripts/functions/wait_for_slot
source /scripts/functions/wait_for_sync
source /scripts/init_node_vars

# Enter staking directory
cd ${NODE_PATH}/staking/
mkdir -p transactions

echo ""
echo "Submitting stake pool certificates to the blockchain."

# Check for required files
if [ ! -f "stake.skey" ]; then
    echo "Missing required stake.skey. You need to run \`generate_stake_address\` to generate this key."
    MISSING_FILES=1
fi

if [ ! -f "payment.skey" ]; then
    echo "Missing required payment.skey. You need to run \`generate_stake_address\` to generate this key."
    MISSING_FILES=1
fi

if [ ! -f "payment.addr" ]; then
    echo "Missing required payment.addr. You need to run \`generate_stake_address\` to generate this key."
    MISSING_FILES=1
fi

if [ ! -f "cold-keys/cold.skey" ]; then
    echo "Missing required staking/cold-keys/cold.skey. You need to run \`generate_operational_certificate\` to generate this key."
    MISSING_FILES=1
fi

if [ ! -f "pool.cert" ]; then
    echo "Missing required staking/pool.cert. You need to run \`generate_registration_certificate\` to generate this certificate."
    MISSING_FILES=1
fi

if [ ! -f "delegation.cert" ]; then
    echo "Missing required staking/delegation.cert. You need to run \`generate_registration_certificate\` to generate this certificate."
    MISSING_FILES=1
fi

if [ -n "$MISSING_FILES" ]; then
    exit
fi

if [ -f "${NODE_PATH}/staking/transactions/register_stake_pool.submitted" ]; then
    echo "Your stake pool has already been registered in the blockchain."
    exit
fi

# Wait for node to sync
wait_for_sync 99

# Generate protocol
cardano-cli shelley query protocol-parameters \
    ${NETWORK_ARGUMENT} \
    --out-file protocol.json

# Get pool-deposit
POOL_DEPOSIT=$(cat protocol.json  | grep poolDeposit | tr ' ' '\n' | tail -1 | sed 's/,//g')

# Get tip
SLOT=$(get_slot)
TTL=$(expr ${SLOT} + 500)

echo "Current tip Slot: ${SLOT}"
echo "TTL: ${TTL}"

## Get the fee
FEE=$(cardano-cli shelley transaction calculate-min-fee \
    --tx-in-count 1 \
    --tx-out-count 1 \
    --ttl ${TTL} \
    ${NETWORK_ARGUMENT} \
    --signing-key-file payment.skey \
    --signing-key-file stake.skey \
    --signing-key-file cold-keys/cold.skey \
    --certificate-file pool.cert \
    --certificate-file delegation.cert \
    --protocol-params-file protocol.json | tr ' ' '\n' | tail -1)
TOTAL_PRICE=$(expr ${FEE} + ${POOL_DEPOSIT})
echo "Fee is: ${FEE}"
echo "Pool-Deposit: ${POOL_DEPOSIT}"
echo "Total Price is: ${TOTAL_PRICE}"

# Find UTXO in address with enough lovelace to do the transaction
ADDRESS=$(cat payment.addr)
check_balance

# Display transaction info
REMAINING_AFTER_TX=$(expr ${LOVELACE} - ${TOTAL_PRICE})
echo "Creating transaction"
echo "UTXO: ${UTXO}#${TXIX}"
echo "Lovelace Holding: ${LOVELACE}"
echo "Lovelace after transaction: ${REMAINING_AFTER_TX}"

#
# Create the transaction
#
cardano-cli shelley transaction build-raw \
    --tx-in "${UTXO}#${TXIX}" \
    --tx-out $(cat payment.addr)+${REMAINING_AFTER_TX} \
    --ttl ${TTL} \
    --fee ${FEE} \
    --out-file transactions/register_stake_pool.raw \
    --certificate-file pool.cert \
    --certificate-file delegation.cert

# Sign the transaction
cardano-cli shelley transaction sign \
    --tx-body-file transactions/register_stake_pool.raw \
    --signing-key-file payment.skey \
    --signing-key-file stake.skey \
    --signing-key-file cold-keys/cold.skey \
    ${NETWORK_ARGUMENT} \
    --out-file transactions/register_stake_pool.signed

# Submit the transaction
OUT=$(cardano-cli shelley transaction submit \
    --tx-file transactions/register_stake_pool.signed \
    ${NETWORK_ARGUMENT})

if [[ $OUT =~ "Error" ]]
then
    echo "An error occoured."
    echo ${OUT}
else
    echo ${OUT}
    touch transactions/register_stake_pool.submitted
    wait_for_slot ${TTL}
    echo "Your stake pool registration has been sent to the blockchain."
fi