#!/bin/bash

# From Documentation
# https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/040_transactions.md
# https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/050_register_key.md

# Init functions and vars
source /scripts/functions/check_balance
source /scripts/init-node-vars
TTL=987654

# Enter staking directory
cd ${NODE_PATH}/staking/
mkdir -p transactions

# Create an address registration certificate
if [ ! -f "${NODE_PATH}/staking/stake.cert" ]; then
    cardano-cli shelley stake-address registration-certificate \
        --staking-verification-key-file stake.vkey \
        --out-file stake.cert
else
    echo "stake.cert certificate already exists."
fi

# Generate protocol
cardano-cli shelley query protocol-parameters \
    ${NETWORK_ARGUMENT} \
    --out-file protocol.json

# Get key-deposit
KEY_DEPOSIT=$(cat protocol.json  | grep keyDeposit | tr ' ' '\n' | tail -1 | sed 's/,//g')

## Get the fee
FEE=$(cardano-cli shelley transaction calculate-min-fee \
    --tx-in-count 1 \
    --tx-out-count 1 \
    --ttl ${TTL} \
    ${NETWORK_ARGUMENT} \
    --signing-key-file payment.skey \
    --signing-key-file stake.skey \
    --certificate-file stake.cert \
    --protocol-params-file protocol.json | tr ' ' '\n' | tail -1)
TOTAL_PRICE=$(expr ${FEE} + ${KEY_DEPOSIT})

echo "Fee is: ${FEE}"
echo "Key-Deposit: ${KEY_DEPOSIT}"
echo "Total Price is: ${TOTAL_PRICE}"

# Find UTXO in address with enough lovelace to do the transaction
ADDRESS=$(cat payment.addr)
check_balance

# Display transaction info
REMAINING_AFTER_TX=$(expr ${LOVELACE} - ${TOTAL_PRICE})
echo "Creating transaction"
echo "UTXO: ${UTXO}"
echo "Lovelace Holding: ${LOVELACE}"
echo "Lovelace after transaction: ${REMAINING_AFTER_TX}"

# Create the transaction
if [ ! -f "${NODE_PATH}/transactions/register_stake_address.submitted" ]; then
    cardano-cli shelley transaction build-raw \
        --tx-in ${UTXO}\#${TXIX} \
        --tx-out $(cat payment.addr)+${REMAINING_AFTER_TX} \
        --ttl ${TTL} \
        --fee ${FEE} \
        --out-file transactions/register_stake_address.raw \
        --certificate-file stake.cert

    # Sign the transaction
    cardano-cli shelley transaction sign \
        --tx-body-file tx.raw \
        --signing-key-file payment.skey \
        --signing-key-file stake.skey \
        ${NETWORK_ARGUMENT} \
        --out-file transactions/register_stake_address.signed

    # Submit the transaction
    cardano-cli shelley transaction submit \
        --tx-file transactions/register_stake_address.signed \
        ${NETWORK_ARGUMENT}
    touch transactions/register_stake_address.submitted
    echo "Your stake key is now registered in the blockchain."
else
    echo "Your stake key has already been registered in the blockchain."
fi