#!/bin/bash

source /scripts/init_node_vars
source /scripts/functions/node_info
source /scripts/functions/check_kes_status

# Check for required files
if [ ! -f "${NODE_PATH}/staking/pool-keys/kes.skey" ]; then
    echo "Missing required kes.skey."
    MISSING_FILES=1
fi

if [ ! -f "${NODE_PATH}/staking/pool-keys/vrf.skey" ]; then
    echo "Missing required vrf.skey."
    MISSING_FILES=1
fi

if [ ! -f "${NODE_PATH}/staking/pool-keys/node.cert" ]; then
    echo "Missing required node.cert."
    MISSING_FILES=1
fi

if [ ! -f "${NODE_PATH}/staking/POOL_ID" ]; then
    echo "Missing required POOL_ID."
    MISSING_FILES=1
fi

if [ -n "$MISSING_FILES" ]; then
    echo "You are missing required files to start."

    if [ -n "$CREATE_STAKEPOOL" ]; then
        create_stakepool
    else
        echo "You need to initialize the stake pool keys, addresses and certificates and submit them to the blockchain first."
        echo "You can do that by running \`create_stakepool\`"
    fi

    exit
else
    echo "Starting Stake Pool."
    node_info 1

    #check_kes_status

    cardano-node run \
        --topology ${NODE_PATH}/topology.json \
        --database-path ${NODE_PATH}/db \
        --socket-path ${CARDANO_NODE_SOCKET_PATH} \
        --host-addr ${HOST_ADDR} \
        --port ${NODE_PORT} \
        --config ${NODE_PATH}/config.json \
        --shelley-kes-key ${NODE_PATH}/staking/pool-keys/kes.skey \
        --shelley-vrf-key ${NODE_PATH}/staking/pool-keys/vrf.skey \
        --shelley-operational-certificate ${NODE_PATH}/staking/pool-keys/node.cert
fi